version: "3.3"
services:
  # api:
  #   build: ./server
  #   image: registry.digitalocean.com/default-swarm-test/api
  #   ports: 
  #     - '8080:8080'
  #   deploy:
  #     replicas: 2
  nginx:
    image: nginx:latest
    ports: 
      - '80:80'
    deploy:
      replicas: 2