version: "3.3"
services:
  api:
    build: ./server
    image: registry.digitalocean.com/default-swarm-test/api
    ports: 
      - '80:8080'
    deploy:
      replicas: 6
  nginx:
    image: nginx:latest
    ports: 
      - '80:80'
    deploy:
      replicas: 2